deployment:
  tasks:
    - export APPPATH=/home/crbvnago/repositories/cms
    - export DEPLOYPATH=/home/crbvnago/public_html

    # Remove old files
    - /bin/rm -rf $DEPLOYPATH/*

    # Copy EVERYTHING from repo to public_html
    - /bin/cp -R $APPPATH/* $DEPLOYPATH/

    # Permissions
    - /bin/chmod -R 775 $DEPLOYPATH/storage
    - /bin/chmod -R 775 $DEPLOYPATH/bootstrap/cache
